### ISSUE TITLE
Not Working on Open Telekom Cloud

### ISSUE THREAD

**Issue by victorgetz** [Huawei/TCP_option_address#8]
Hi is there any Chance that this will run on the Open Telekom Cloud?

If i run this module on my Node i get the following Error:

![image](https://user-images.githubusercontent.com/19291722/114511678-85185c80-9c38-11eb-8355-f8597df4e2f1.png)

The ../build File exists and the Path is correct.

**Comment by spielkind** [comment]
build is probably a broken symlink to /usr/src/kernels ... I guess you have to install "yum install kernel-devel kernel-headers gcc make"

Anyway, the EulerOS Image on OTC has a prebuild package, there is no need to compile it at your own:
```
$ yum search toa
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
============================================================================================================= N/S matched: toa ==============================================================================================================
ipvs-toa.x86_64 : Ipvs Toa  kernel modules
kmod-toa.x86_64 : toa kernel module(s)
toa.x86_64 : Huawei TCP Option Address kernel module

```
